"""
Django settings for dst_mrz_parent project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iybt4-@2o9mm8do-)ifh3!+v8n609gzr49rkl!ij7-f9lqvwzf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'modules.dst_mrz_app',
    'modules.dst_mrz_maintenance',
    'modules.dst_mrz_s3',
    'modules.mrz_reader',
    'modules.ocr_paddleocr',
]

MIDDLEWARE = [
    'dst_mrz_parent.middleware.ErrorHandlerMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dst_mrz_parent.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dst_mrz_parent.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "%(levelname)s %(asctime)s %(module)s [%(process)d:%(thread)d] %(message)s"
        },
        "simple": {"format": "%(levelname)s %(message)s"},
    },
    "handlers": {
        "dst-mrz-be": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": "C:/Users/USER/Documents/data/logs/dst-mrz-be.log",
            #"filename": "C:/Users/USER/Documents/TEST/logs/dst-mrz-be.log",
            "when": "midnight",
            "backupCount": 7,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "dst-mrz-be": {
            "handlers": ["dst-mrz-be"],
            "level": "DEBUG",
            "propagate": True,
        },
        "django": {
            "handlers": ["dst-mrz-be"],  # Use the same handler as "logit"
            "level": "INFO",
            "propagate": True,
        },
    },
}

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #    'ENGINE': 'django.db.backends.mysql',
    #    'NAME': 'ekyc',
    #    'USER': 'ekyc',
    #    'PASSWORD': 'password',
    #    'HOST': 'localhost',
    #    'PORT': '3306',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'rds_ekyc_uat',
        'USER': 'ekycuat',
        'PASSWORD': 'Ekyc$uat7890$!',
        'HOST': 'stack-eathl3dyeffowhra9-rdsinstance-hhvrsetupfwq.c4gx4xv2vovl.ap-southeast-1.rds.amazonaws.com',
        'PORT': '3306',
    },
    # 'default': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'rds_ekyc_uat',
    #     'USER': 'ekycuat',
    #     'PASSWORD': 'Ekyc$uat7890$!',
    #     'HOST': 'stack-eathl3dyeffowhra9-rdsinstance-hhvrsetupfwq.c4gx4xv2vovl.ap-southeast-1.rds.amazonaws.com',
    #     'PORT': '3306',
    # },
}

S3 = {
    "MRZ": {
        'bucket_name' : "uat-ekyc-bucket-364309113007",
        'suffix' : 'mrz/'
    },
}